document.onclick=function(event){var el=event.target;function getSelectedSection(){return(document.querySelector('.section-selected')&&document.querySelector('.section-selected').dataset.jsSection)||'Exercises'}
if(el.classList.contains("section-button")){var selectedElement=document.getElementsByClassName('section-selected')[0];var menu=document.getElementById('section_options');menu.classList.remove('section-options--open');if(el.classList.contains("close-menu-button")){return;}
selectedElement&&selectedElement.classList.remove("section-selected");localStorage.removeItem("section");if(el.classList.contains("default-menu-button")){return;}
if(selectedElement!=el){el.classList.add("section-selected");localStorage.setItem("section",getSelectedSection());}
event.stopPropagation();}

if(el.classList.contains("show-sections-button")){var menu=document.getElementById('section_options');menu.classList.add('section-options--open');event.stopPropagation();}
if(hasInParentsUntil(event.target,'sexchoosermalelabel',document)){document.getElementById("femalefigures").style.display="none";document.getElementById("malefigures").style.display="block";localStorage.setItem("sex","m");event.stopPropagation();}
if(hasInParentsUntil(event.target,'sexchooserfemalelabel',document)){document.getElementById("malefigures").style.display="none";document.getElementById("femalefigures").style.display="block";localStorage.setItem("sex","f");event.stopPropagation();}

if(el.nodeName=="IMG"){switch(el.id)
    {case "traps-a":case "female-traps-a":window.location="#Trapecio";break;case "traps-b":case "female-traps-b":window.location="#Trapecio";break;case "shoulders-a":case "female-shoulders-a":window.location="#Hombros";break;case "shoulders-b":case "female-shoulders-b":window.location="#Hombros";break;case "pecs":case "female-pecs":window.location="#Peito";break;case "biceps-a":case "female-biceps-a":window.location="#Biceps";break;case "biceps-b":case "female-biceps-b":window.location="#Biceps";break;case "forearm-a":case "female-forearm-a":window.location="#Biceps";break;case "forearm-b":case "female-forearm-b":window.location="#Biceps";break;case "obliques":case "female-abdominals":window.location="#Abdominales";break;case "quads-a":case "female-quads-a":window.location="#Pernas";break;case "quads-b":case "female-quads-b":window.location="#Pernas";break;case "calves-a":case "female-calves-a":window.location="#Gemeos";break;case "calves-b":case "female-calves-b":window.location="#Gemeos";break;case "back-traps-a":case "female-back-traps-a":window.location="#Trapecio";break;case "back-traps-b":case "female-back-traps-b":window.location="#Dorsais";break;case "back-shoulders-a":case "female-back-shoulders-a":window.location="#Hombros";break;case "back-shoulders-b":case "female-back-shoulders-b":window.location="#Hombros";break;case "triceps-a":case "female-triceps-a":window.location="#Triceps";break;case "triceps-b":case "female-triceps-b":window.location="#Triceps";break;case "back-upper-a":case "female-back-upper-a":window.location="#Dorsais";break;case "back-upper-b":case "female-back-upper-b":window.location="#Dorsais";break;case "back-lats-a":case "female-back-lats-a":window.location="#Dorsais";break;case "back-lats-b":case "female-back-lats-b":window.location="#Dorsais";break;case "back-lower":case "female-back-lower":window.location="/"+type_url+"/"+gender+"/Lowerback";break;case "back-forearms-a":case "female-back-forearms-a":window.location="#Biceps";break;case "back-forearms-b":case "female-back-forearms-b":window.location="#Biceps";break;case "back-glutes":case "female-back-glutes":window.location="#Gluteus";break;case "back-hamstrings-a":case "female-back-hamstrings-a":window.location="#Pernas";break;case "back-hamstrings-b":case "female-back-hamstrings-b":window.location="#Pernas";break;case "back-calves-a":case "female-back-calves-a":window.location="#Gemeos";break;case "back-calves-b":case "female-back-calves-b":window.location="#Gemeos";break;}}};function resizeIframe(obj){obj.style.height=obj.contentWindow.document.body.scrollHeight+'px';}
function hasInParentsUntil(el,id,limit){if(el.id===id)return true;if(el===limit)return false;if(el.parentNode)return hasInParentsUntil(el.parentNode,id,limit);return false;}
function loadSelections(selecton){if(!selecton)return;if(typeof selecton.onclick=="function"){selecton.onclick();}else if(typeof selecton.click=="function"){selecton.click();}}
document.addEventListener("DOMContentLoaded",function(){console.log("DOMContentLoaded");randGender=(Math.floor(Math.random()*2)==0)?'m':'f';var _sex=localStorage.getItem("sex")||randGender;var section=localStorage.getItem("section")||'Exercise';var _sex_el=_sex=="m"?document.getElementById("sexchoosermalelabel"):document.getElementById("sexchooserfemalelabel");loadSelections(_sex_el);var _section_el=document.querySelectorAll(`[data-js-section='${section}']`)[0];loadSelections(_section_el);});